sudo: false
dist: trusty
language: python
python: 3.7-dev

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

addons:
  sonarcloud:
    organization: "cryptic-game"
    token:
      secure: "g7VZQdEf7gn0WsMmqLlaKSXqnjIA6/diTroMAeXYBlTn/CMMjF63n6xrcqgDQcKCJvqsZ3BKl1OqXZiJV4jZV1c3rCeTr/tXr5/EkqcBUMWWwDRAXYzlOE36GRwnspozHXDLLRm5zuUcPC7f4UqoIsoT7K9WwmSLmjyHnq1rQH4+pX0mBQB5B55PgDSkCZk1pF1w0DlpEJhjCHtfBGWfOlNqLe3OO+g0HE4Yn7C7b/NR5tJT0I1KDoLlbDEnvxTd8cT08EwBAvPUldcvXQqaZsyQQlvZIoze8juOPNfADddbkGh6W8jYaCrF+JHsa4MLw9zfXiQkUVOJjS2jZWxhKianKFChwdnijyQjsvuj8u+aEhMRgN+t9WSNi3SDfN0UIv1tF2JgyozQchNju8gmkwtM0jeddgVHyFW7RuW3eUOWu1ut4wIA/u5JqC+vEZ5uW4cIVPmWiRVYI/Jv8JyoPzt47EtfDAlBe2gV1g+cOXLhHpuq1vNlyoaq0zGR+vIE4JmvuP2JUoQP6G8CDtsHUP6/Nq9hXgTR+3ubSNmG9aoaP/1vAIySfZ+L+tfNg4PmZ2Fq7forQOmBBU8Bj2yVNJA7rE3QDCLMvZ9MZewVh5F66+O/zIk/bANEaXAWJcqRLuZfj0T4x3l2EOFfkCmZ3/N40MUMm3aMOfI5y1tsLAk="

install:
- cd app/ && pip install pipenv && pipenv install --dev
script:
- pipenv run coverage_travis
- sonar-scanner
after_success:
- pipenv run coveralls
